# Generated by Django 3.0.6 on 2020-05-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(default='', max_length=1000)),
                ('label', models.CharField(default=None, max_length=15)),
                ('star', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('isbn_code', models.CharField(default='0000000000000', max_length=13)),
                ('title', models.TextField(default='')),
                ('subtitle', models.TextField(default='')),
                ('authors', models.TextField(default='')),
                ('published_date', models.CharField(default=None, max_length=8)),
                ('description', models.TextField(default='')),
                ('img_url', models.TextField(default='')),
                ('was_read', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
